version: "3.9"

services:
  db:
    image: postgres
    extra_hosts:
      - host.docker.internal:host-gateway # 追記
    platform: linux/amd64
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=django_develop
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "psql -U postgres"
      interval: 5s
      timeout: 5s
      retries: 5


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    environment:
      - DEBUG=1
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
