# Generated by Django 5.0.6 on 2024-06-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('discription', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Ec_ProductModel',
            },
        ),
    ]
