# Generated by Django 4.2.5 on 2024-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='discription',
            field=models.CharField(default=1111, max_length=20),
            preserve_default=False,
        ),
    ]
