# Generated by Django 5.0.6 on 2024-06-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lastname', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('holder', models.CharField(max_length=20)),
                ('credit_card_number', models.IntegerField()),
                ('date_of_expiry', models.DateField()),
                ('security_code', models.IntegerField()),
            ],
            options={
                'db_table': 'Ec_OrderdModel',
            },
        ),
    ]
