# Generated by Django 4.2.5 on 2024-06-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='products',
            field=models.ManyToManyField(through='ec.CartItemModel', to='ec.productmodel'),
        ),
    ]
