# Generated by Django 4.2.5 on 2024-06-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0002_cartmodel_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='products',
        ),
    ]
