# Generated by Django 4.2.5 on 2024-07-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0003_remove_cartmodel_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitemmodel',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitemmodel',
            old_name='name',
            new_name='product',
        ),
    ]
