# Generated by Django 4.2.5 on 2024-07-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0005_rename_cart_id_cartmodel_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='name',
            new_name='product',
        ),
    ]
